name: playlistr
channels:
  - defaults
dependencies:
  - aiohttp=3.9.3
  - aiosignal=1.2.0
  - attrs=23.1.0
  - black=23.11.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - cryptography=41.0.7
  - debugpy=1.6.7
  - expat=2.5.0
  - frozenlist=1.4.0
  - idna=3.4
  - iniconfig=1.1.1
  - libcxx=14.0.6
  - libffi=3.4.4
  - multidict=6.0.4
  - mypy_extensions=1.0.0
  - ncurses=6.4
  - openssl=3.0.13
  - packaging=23.1
  - pathspec=0.10.3
  - pip=23.3.1
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - pycparser=2.21
  - pyjwt=2.4.0
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - pytest=7.4.0
  - python=3.12.1
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023d
  - urllib3=1.26.18
  - wheel=0.41.2
  - xz=5.4.5
  - yarl=1.9.3
  - zlib=1.2.13
  - pip:
      - oauthlib==3.2.2
