[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mussty"
description = "A streaming service migration CLI tool."
dynamic = ["version"]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = [
  "src"
]

[tool.hatch]
